In [1]:
print("Hello Avishi")

Hello Avishi

In [1]:
import pandas as pd

In [3]:
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

In [5]:
fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [6]:
fund_master.shape

(40, 15)

In [7]:
fund_master.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [8]:
fund_master.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [9]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [10]:
fund_master.duplicated().sum()

np.int64(0)

In [11]:
fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [12]:
import pandas as pd
import os

folder = "../data/raw"

for file in os.listdir(folder):

    if file.endswith(".csv"):

        print("\n" + "="*60)
        print("FILE:", file)

        df = pd.read_csv(os.path.join(folder, file))

        print("\nSHAPE:")
        print(df.shape)

        print("\nDTYPES:")
        print(df.dtypes)

        print("\nFIRST 5 ROWS:")
        print(df.head())

============================================================
FILE: 01_fund_master.csv

SHAPE:
(40, 15)

DTYPES:
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

FIRST 5 ROWS:
   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02

============================================================
FILE: 02_nav_history.csv

SHAPE:
(46000, 3)

DTYPES:
amfi_code      int64
date             str
nav          float64
dtype: object

FIRST 5 ROWS:
   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

============================================================
FILE: 03_aum_by_fund_house.csv

SHAPE:
(90, 5)

DTYPES:
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

FIRST 5 ROWS:
         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

============================================================
FILE: 04_monthly_sip_inflows.csv

SHAPE:
(48, 6)

DTYPES:
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

FIRST 5 ROWS:
     month  sip_inflow_crore  active_sip_accounts_crore  \
0  2022-01             11517                       4.91
1  2022-02             11438                       4.93
2  2022-03             12328                       5.09
3  2022-04             11863                       5.48
4  2022-05             12286                       5.55

   new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct
0                   9.10                4.80             NaN
1                   8.20                4.85             NaN
2                  10.50                5.01             NaN
3                   9.52                5.12             NaN
4                   8.10                5.15             NaN

============================================================
FILE: 05_category_inflows.csv

SHAPE:
(144, 3)

DTYPES:
month                   str
category                str
net_inflow_crore    float64
dtype: object

FIRST 5 ROWS:
     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

============================================================
FILE: 06_industry_folio_count.csv

SHAPE:
(21, 6)

DTYPES:
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

FIRST 5 ROWS:
     month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0  2022-01               13.26                 9.28               1.86
1  2022-04               13.91                 9.74               1.95
2  2022-07               13.85                 9.69               1.94
3  2022-10               14.12                 9.88               1.98
4  2023-01               14.81                10.37               2.07

   hybrid_folios_crore  others_folios_crore
0                 0.80                 1.33
1                 0.83                 1.39
2                 0.83                 1.38
3                 0.85                 1.41
4                 0.89                 1.48

============================================================
FILE: 07_scheme_performance.csv

SHAPE:
(40, 19)

DTYPES:
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

FIRST 5 ROWS:
   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low

============================================================
FILE: 08_investor_transactions.csv

SHAPE:
(32778, 13)

DTYPES:
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

FIRST 5 ROWS:
  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending

============================================================
FILE: 09_portfolio_holdings.csv

SHAPE:
(322, 8)

DTYPES:
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

FIRST 5 ROWS:
   amfi_code stock_symbol                stock_name       sector  weight_pct  \
0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85
1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19
2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90
3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76
4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25

   market_value_cr  current_price_inr portfolio_date
0           737.09            6011.08     2025-12-31
1            88.97            1074.65     2025-12-31
2           208.45            5964.59     2025-12-31
3           161.32            3748.82     2025-12-31
4           725.90            1321.45     2025-12-31

============================================================
FILE: 10_benchmark_indices.csv

SHAPE:
(8050, 3)

DTYPES:
date               str
index_name         str
close_value    float64
dtype: object

FIRST 5 ROWS:
         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [16]:
import pandas as pd
import os

folder = "../data/raw"

for file in os.listdir(folder):

    if file.endswith(".csv"):

        print("\n" + "="*60)
        print("DATASET:", file)

        df = pd.read_csv(os.path.join(folder, file))

        print("\nShape:")
        print(df.shape)

        print("\nData Types:")
        print(df.dtypes)

        print("\nFirst 5 Rows:")
        print(df.head())

        print("\nMissing Values:")
        print(df.isnull().sum().sum())

        print("\nDuplicate Rows:")
        print(df.duplicated().sum())

============================================================
DATASET: 01_fund_master.csv

Shape:
(40, 15)

Data Types:
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

First 5 Rows:
   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02

Missing Values:
0

Duplicate Rows:
0

============================================================
DATASET: 02_nav_history.csv

Shape:
(46000, 3)

Data Types:
amfi_code      int64
date             str
nav          float64
dtype: object

First 5 Rows:
   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

Missing Values:
0

Duplicate Rows:
0

============================================================
DATASET: 03_aum_by_fund_house.csv

Shape:
(90, 5)

Data Types:
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

First 5 Rows:
         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

Missing Values:
0

Duplicate Rows:
0

============================================================
DATASET: 04_monthly_sip_inflows.csv

Shape:
(48, 6)

Data Types:
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

First 5 Rows:
     month  sip_inflow_crore  active_sip_accounts_crore  \
0  2022-01             11517                       4.91
1  2022-02             11438                       4.93
2  2022-03             12328                       5.09
3  2022-04             11863                       5.48
4  2022-05             12286                       5.55

   new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct
0                   9.10                4.80             NaN
1                   8.20                4.85             NaN
2                  10.50                5.01             NaN
3                   9.52                5.12             NaN
4                   8.10                5.15             NaN

Missing Values:
12

Duplicate Rows:
0

============================================================
DATASET: 05_category_inflows.csv

Shape:
(144, 3)

Data Types:
month                   str
category                str
net_inflow_crore    float64
dtype: object

First 5 Rows:
     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

Missing Values:
0

Duplicate Rows:
0

============================================================
DATASET: 06_industry_folio_count.csv

Shape:
(21, 6)

Data Types:
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

First 5 Rows:
     month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0  2022-01               13.26                 9.28               1.86
1  2022-04               13.91                 9.74               1.95
2  2022-07               13.85                 9.69               1.94
3  2022-10               14.12                 9.88               1.98
4  2023-01               14.81                10.37               2.07

   hybrid_folios_crore  others_folios_crore
0                 0.80                 1.33
1                 0.83                 1.39
2                 0.83                 1.38
3                 0.85                 1.41
4                 0.89                 1.48

Missing Values:
0

Duplicate Rows:
0

============================================================
DATASET: 07_scheme_performance.csv

Shape:
(40, 19)

Data Types:
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

First 5 Rows:
   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low

Missing Values:
0

Duplicate Rows:
0

============================================================
DATASET: 08_investor_transactions.csv

Shape:
(32778, 13)

Data Types:
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

First 5 Rows:
  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending

Missing Values:
0

Duplicate Rows:
0

============================================================
DATASET: 09_portfolio_holdings.csv

Shape:
(322, 8)

Data Types:
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

First 5 Rows:
   amfi_code stock_symbol                stock_name       sector  weight_pct  \
0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85
1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19
2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90
3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76
4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25

   market_value_cr  current_price_inr portfolio_date
0           737.09            6011.08     2025-12-31
1            88.97            1074.65     2025-12-31
2           208.45            5964.59     2025-12-31
3           161.32            3748.82     2025-12-31
4           725.90            1321.45     2025-12-31

Missing Values:
0

Duplicate Rows:
0

============================================================
DATASET: 10_benchmark_indices.csv

Shape:
(8050, 3)

Data Types:
date               str
index_name         str
close_value    float64
dtype: object

First 5 Rows:
         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

Missing Values:
0

Duplicate Rows:
0

In [17]:
fund_master["fund_house"].unique()

<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

In [18]:
fund_master["category"].unique()

<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

In [19]:
fund_master["sub_category"].unique()

<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

In [20]:
fund_master["risk_category"].unique()

<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

In [21]:
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")

In [22]:
nav_history.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [23]:
fund_master.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [24]:
master_codes = set(fund_master["amfi_code"])

In [25]:
nav_codes = set(nav_history["amfi_code"])

In [26]:
len(master_codes)

40

In [27]:
len(nav_codes)

40

In [28]:
missing_codes = master_codes - nav_codes

missing_codes
|

SyntaxError: invalid syntax (1459498227.py, line 4)

In [29]:
missing_codes = master_codes - nav_codes

missing_codes

set()

In [30]:
extra_codes = nav_codes - master_codes

extra_codes

set()

In [32]:
import requests

In [33]:
import requests

url = "https://api.mfapi.in/mf/125497"

response = requests.get(url)

print(response.status_code)

200

In [34]:
data = response.json()

data

{'meta': {'fund_house': 'SBI Mutual Fund',
  'scheme_type': 'Open Ended Schemes',
  'scheme_category': 'Equity Scheme - Small Cap Fund',
  'scheme_code': 125497,
  'scheme_name': 'SBI Small Cap Fund - Direct Plan - Growth',
  'isin_growth': 'INF200K01T51',
  'isin_div_reinvestment': None},
 'data': [{'date': '02-06-2026', 'nav': '193.12950'},
  {'date': '01-06-2026', 'nav': '192.31950'},
  {'date': '31-05-2026', 'nav': '193.68360'},
  {'date': '29-05-2026', 'nav': '193.68480'},
  {'date': '27-05-2026', 'nav': '195.05010'},
  {'date': '26-05-2026', 'nav': '194.22580'},
  {'date': '25-05-2026', 'nav': '193.55990'},
  {'date': '22-05-2026', 'nav': '192.12270'},
  {'date': '21-05-2026', 'nav': '191.75750'},
  {'date': '20-05-2026', 'nav': '189.86610'},
  {'date': '19-05-2026', 'nav': '189.55530'},
  {'date': '18-05-2026', 'nav': '187.91260'},
  {'date': '15-05-2026', 'nav': '190.24050'},
  {'date': '14-05-2026', 'nav': '189.93450'},
  {'date': '13-05-2026', 'nav': '190.46400'},
  {'date': '12-05-2026', 'nav': '190.61520'},
  {'date': '11-05-2026', 'nav': '195.58600'},
  {'date': '08-05-2026', 'nav': '196.88210'},
  {'date': '07-05-2026', 'nav': '197.47530'},
  {'date': '06-05-2026', 'nav': '196.00360'},
  {'date': '05-05-2026', 'nav': '194.56180'},
  {'date': '04-05-2026', 'nav': '195.44690'},
  {'date': '30-04-2026', 'nav': '193.41310'},
  {'date': '29-04-2026', 'nav': '194.15230'},
  {'date': '28-04-2026', 'nav': '193.48430'},
  {'date': '27-04-2026', 'nav': '193.83170'},
  {'date': '24-04-2026', 'nav': '191.04250'},
  {'date': '23-04-2026', 'nav': '193.03170'},
  {'date': '22-04-2026', 'nav': '194.19280'},
  {'date': '21-04-2026', 'nav': '192.63970'},
  {'date': '20-04-2026', 'nav': '191.05830'},
  {'date': '17-04-2026', 'nav': '190.52420'},
  {'date': '16-04-2026', 'nav': '188.33160'},
  {'date': '15-04-2026', 'nav': '187.27860'},
  {'date': '13-04-2026', 'nav': '184.34910'},
  {'date': '10-04-2026', 'nav': '184.69670'},
  {'date': '09-04-2026', 'nav': '181.24550'},
  {'date': '08-04-2026', 'nav': '180.57830'},
  {'date': '07-04-2026', 'nav': '174.83420'},
  {'date': '06-04-2026', 'nav': '174.91510'},
  {'date': '02-04-2026', 'nav': '173.84710'},
  {'date': '01-04-2026', 'nav': '173.78200'},
  {'date': '31-03-2026', 'nav': '169.37060'},
  {'date': '30-03-2026', 'nav': '169.37080'},
  {'date': '27-03-2026', 'nav': '172.47390'},
  {'date': '25-03-2026', 'nav': '175.42110'},
  {'date': '24-03-2026', 'nav': '172.00490'},
  {'date': '23-03-2026', 'nav': '169.10910'},
  {'date': '20-03-2026', 'nav': '174.62050'},
  {'date': '19-03-2026', 'nav': '173.90040'},
  {'date': '18-03-2026', 'nav': '177.49080'},
  {'date': '17-03-2026', 'nav': '174.06280'},
  {'date': '16-03-2026', 'nav': '173.81980'},
  {'date': '13-03-2026', 'nav': '173.97540'},
  {'date': '12-03-2026', 'nav': '177.98880'},
  {'date': '11-03-2026', 'nav': '178.38910'},
  {'date': '10-03-2026', 'nav': '178.84190'},
  {'date': '09-03-2026', 'nav': '175.77420'},
  {'date': '06-03-2026', 'nav': '178.97840'},
  {'date': '05-03-2026', 'nav': '179.32390'},
  {'date': '04-03-2026', 'nav': '177.99610'},
  {'date': '02-03-2026', 'nav': '181.31750'},
  {'date': '28-02-2026', 'nav': '184.75790'},
  {'date': '27-02-2026', 'nav': '184.75810'},
  {'date': '26-02-2026', 'nav': '186.09500'},
  {'date': '25-02-2026', 'nav': '186.04880'},
  {'date': '24-02-2026', 'nav': '186.20800'},
  {'date': '23-02-2026', 'nav': '187.57210'},
  {'date': '20-02-2026', 'nav': '186.22280'},
  {'date': '19-02-2026', 'nav': '186.66660'},
  {'date': '18-02-2026', 'nav': '188.21280'},
  {'date': '17-02-2026', 'nav': '187.64370'},
  {'date': '16-02-2026', 'nav': '185.84710'},
  {'date': '13-02-2026', 'nav': '187.23600'},
  {'date': '12-02-2026', 'nav': '189.60290'},
  {'date': '11-02-2026', 'nav': '189.74640'},
  {'date': '10-02-2026', 'nav': '189.01900'},
  {'date': '09-02-2026', 'nav': '188.46900'},
  {'date': '06-02-2026', 'nav': '184.62700'},
  {'date': '05-02-2026', 'nav': '185.69490'},
  {'date': '04-02-2026', 'nav': '186.77740'},
  {'date': '03-02-2026', 'nav': '186.70090'},
  {'date': '02-02-2026', 'nav': '180.54240'},
  {'date': '31-01-2026', 'nav': '183.30100'},
  {'date': '30-01-2026', 'nav': '183.30210'},
  {'date': '29-01-2026', 'nav': '179.94080'},
  {'date': '28-01-2026', 'nav': '181.08730'},
  {'date': '27-01-2026', 'nav': '179.55150'},
  {'date': '23-01-2026', 'nav': '179.80350'},
  {'date': '22-01-2026', 'nav': '182.75440'},
  {'date': '21-01-2026', 'nav': '181.53250'},
  {'date': '20-01-2026', 'nav': '181.83500'},
  {'date': '19-01-2026', 'nav': '185.40420'},
  {'date': '16-01-2026', 'nav': '186.97190'},
  {'date': '14-01-2026', 'nav': '187.33750'},
  {'date': '13-01-2026', 'nav': '187.65940'},
  {'date': '12-01-2026', 'nav': '186.18370'},
  {'date': '09-01-2026', 'nav': '187.09710'},
  {'date': '08-01-2026', 'nav': '190.16000'},
  {'date': '07-01-2026', 'nav': '193.31730'},
  {'date': '06-01-2026', 'nav': '193.70270'},
  {'date': '05-01-2026', 'nav': '194.37860'},
  {'date': '02-01-2026', 'nav': '194.57400'},
  {'date': '01-01-2026', 'nav': '193.64170'},
  {'date': '31-12-2025', 'nav': '193.77240'},
  {'date': '30-12-2025', 'nav': '191.95010'},
  {'date': '29-12-2025', 'nav': '192.54100'},
  {'date': '26-12-2025', 'nav': '192.59130'},
  {'date': '24-12-2025', 'nav': '193.28480'},
  {'date': '23-12-2025', 'nav': '193.26520'},
  {'date': '22-12-2025', 'nav': '192.25730'},
  {'date': '19-12-2025', 'nav': '191.11570'},
  {'date': '18-12-2025', 'nav': '189.54200'},
  {'date': '17-12-2025', 'nav': '190.06210'},
  {'date': '16-12-2025', 'nav': '191.31430'},
  {'date': '15-12-2025', 'nav': '193.13250'},
  {'date': '12-12-2025', 'nav': '192.33770'},
  {'date': '11-12-2025', 'nav': '191.49520'},
  {'date': '10-12-2025', 'nav': '191.25570'},
  {'date': '09-12-2025', 'nav': '191.35730'},
  {'date': '08-12-2025', 'nav': '190.15910'},
  {'date': '05-12-2025', 'nav': '193.14510'},
  {'date': '04-12-2025', 'nav': '193.45990'},
  {'date': '03-12-2025', 'nav': '194.33550'},
  {'date': '02-12-2025', 'nav': '194.43120'},
  {'date': '01-12-2025', 'nav': '195.36260'},
  {'date': '30-11-2025', 'nav': '194.97900'},
  {'date': '28-11-2025', 'nav': '194.97840'},
  {'date': '27-11-2025', 'nav': '195.14900'},
  {'date': '26-11-2025', 'nav': '195.85550'},
  {'date': '25-11-2025', 'nav': '194.20420'},
  {'date': '24-11-2025', 'nav': '193.90920'},
  {'date': '21-11-2025', 'nav': '194.25170'},
  {'date': '20-11-2025', 'nav': '196.07320'},
  {'date': '19-11-2025', 'nav': '196.52800'},
  {'date': '18-11-2025', 'nav': '196.94780'},
  {'date': '17-11-2025', 'nav': '197.92120'},
  {'date': '14-11-2025', 'nav': '197.06760'},
  {'date': '13-11-2025', 'nav': '196.54650'},
  {'date': '12-11-2025', 'nav': '196.88400'},
  {'date': '11-11-2025', 'nav': '196.44860'},
  {'date': '10-11-2025', 'nav': '196.24510'},
  {'date': '07-11-2025', 'nav': '197.31500'},
  {'date': '06-11-2025', 'nav': '197.80320'},
  {'date': '04-11-2025', 'nav': '200.46780'},
  {'date': '03-11-2025', 'nav': '200.97090'},
  {'date': '31-10-2025', 'nav': '199.82340'},
  {'date': '30-10-2025', 'nav': '200.51850'},
  {'date': '29-10-2025', 'nav': '201.03750'},
  {'date': '28-10-2025', 'nav': '200.63480'},
  {'date': '27-10-2025', 'nav': '199.79650'},
  {'date': '24-10-2025', 'nav': '198.41150'},
  {'date': '23-10-2025', 'nav': '198.75210'},
  {'date': '20-10-2025', 'nav': '197.52580'},
  {'date': '17-10-2025', 'nav': '197.10750'},
  {'date': '16-10-2025', 'nav': '196.95210'},
  {'date': '15-10-2025', 'nav': '194.70000'},
  {'date': '14-10-2025', 'nav': '193.39750'},
  {'date': '13-10-2025', 'nav': '194.53640'},
  {'date': '10-10-2025', 'nav': '195.11850'},
  {'date': '09-10-2025', 'nav': '195.03760'},
  {'date': '08-10-2025', 'nav': '195.85870'},
  {'date': '07-10-2025', 'nav': '196.42940'},
  {'date': '06-10-2025', 'nav': '196.54830'},
  {'date': '03-10-2025', 'nav': '196.29650'},
  {'date': '01-10-2025', 'nav': '195.08560'},
  {'date': '30-09-2025', 'nav': '193.88220'},
  {'date': '26-09-2025', 'nav': '194.09730'},
  {'date': '25-09-2025', 'nav': '197.34470'},
  {'date': '24-09-2025', 'nav': '198.88610'},
  {'date': '23-09-2025', 'nav': '199.45730'},
  {'date': '22-09-2025', 'nav': '200.25390'},
  {'date': '19-09-2025', 'nav': '201.30600'},
  {'date': '18-09-2025', 'nav': '201.54470'},
  {'date': '17-09-2025', 'nav': '201.82000'},
  {'date': '16-09-2025', 'nav': '201.17950'},
  {'date': '15-09-2025', 'nav': '200.09670'},
  {'date': '12-09-2025', 'nav': '199.07160'},
  {'date': '11-09-2025', 'nav': '198.98350'},
  {'date': '10-09-2025', 'nav': '198.70750'},
  {'date': '09-09-2025', 'nav': '198.24440'},
  {'date': '08-09-2025', 'nav': '197.44800'},
  {'date': '05-09-2025', 'nav': '197.59390'},
  {'date': '04-09-2025', 'nav': '197.68870'},
  {'date': '03-09-2025', 'nav': '197.63250'},
  {'date': '02-09-2025', 'nav': '196.23670'},
  {'date': '01-09-2025', 'nav': '195.73430'},
  {'date': '31-08-2025', 'nav': '193.75370'},
  {'date': '29-08-2025', 'nav': '193.75320'},
  {'date': '28-08-2025', 'nav': '194.48930'},
  {'date': '26-08-2025', 'nav': '195.59460'},
  {'date': '25-08-2025', 'nav': '198.78050'},
  {'date': '22-08-2025', 'nav': '199.11560'},
  {'date': '21-08-2025', 'nav': '200.05540'},
  {'date': '20-08-2025', 'nav': '198.84770'},
  {'date': '19-08-2025', 'nav': '198.03890'},
  {'date': '18-08-2025', 'nav': '196.92030'},
  {'date': '14-08-2025', 'nav': '193.41310'},
  {'date': '13-08-2025', 'nav': '192.92220'},
  {'date': '12-08-2025', 'nav': '192.70500'},
  {'date': '11-08-2025', 'nav': '193.15840'},
  {'date': '08-08-2025', 'nav': '191.95750'},
  {'date': '07-08-2025', 'nav': '193.00640'},
  {'date': '06-08-2025', 'nav': '193.57560'},
  {'date': '05-08-2025', 'nav': '194.97310'},
  {'date': '04-08-2025', 'nav': '195.65360'},
  {'date': '01-08-2025', 'nav': '194.95480'},
  {'date': '31-07-2025', 'nav': '197.48900'},
  {'date': '30-07-2025', 'nav': '198.45080'},
  {'date': '29-07-2025', 'nav': '197.81460'},
  {'date': '28-07-2025', 'nav': '197.46290'},
  {'date': '25-07-2025', 'nav': '199.43490'},
  {'date': '24-07-2025', 'nav': '202.72100'},
  {'date': '23-07-2025', 'nav': '203.90430'},
  {'date': '22-07-2025', 'nav': '203.37140'},
  {'date': '21-07-2025', 'nav': '203.80280'},
  {'date': '18-07-2025', 'nav': '204.03560'},
  {'date': '17-07-2025', 'nav': '204.90430'},
  {'date': '16-07-2025', 'nav': '203.68350'},
  {'date': '15-07-2025', 'nav': '203.92680'},
  {'date': '14-07-2025', 'nav': '202.01890'},
  {'date': '11-07-2025', 'nav': '201.26060'},
  {'date': '10-07-2025', 'nav': '201.59850'},
  {'date': '09-07-2025', 'nav': '201.32870'},
  {'date': '08-07-2025', 'nav': '200.43960'},
  {'date': '07-07-2025', 'nav': '200.32350'},
  {'date': '04-07-2025', 'nav': '200.67620'},
  {'date': '03-07-2025', 'nav': '200.01860'},
  {'date': '02-07-2025', 'nav': '199.34090'},
  {'date': '01-07-2025', 'nav': '200.26720'},
  {'date': '30-06-2025', 'nav': '200.31780'},
  {'date': '27-06-2025', 'nav': '198.06880'},
  {'date': '26-06-2025', 'nav': '197.22860'},
  {'date': '25-06-2025', 'nav': '197.44050'},
  {'date': '24-06-2025', 'nav': '194.48380'},
  {'date': '23-06-2025', 'nav': '192.97300'},
  {'date': '20-06-2025', 'nav': '192.58720'},
  {'date': '19-06-2025', 'nav': '192.15350'},
  {'date': '18-06-2025', 'nav': '194.74980'},
  {'date': '17-06-2025', 'nav': '194.49760'},
  {'date': '16-06-2025', 'nav': '194.31170'},
  {'date': '13-06-2025', 'nav': '193.87020'},
  {'date': '12-06-2025', 'nav': '194.31590'},
  {'date': '11-06-2025', 'nav': '196.31550'},
  {'date': '10-06-2025', 'nav': '196.32030'},
  {'date': '09-06-2025', 'nav': '196.22680'},
  {'date': '06-06-2025', 'nav': '194.43670'},
  {'date': '05-06-2025', 'nav': '193.46220'},
  {'date': '04-06-2025', 'nav': '193.32410'},
  {'date': '03-06-2025', 'nav': '193.35580'},
  {'date': '02-06-2025', 'nav': '193.01410'},
  {'date': '31-05-2025', 'nav': '192.67840'},
  {'date': '30-05-2025', 'nav': '192.67720'},
  {'date': '29-05-2025', 'nav': '192.49060'},
  {'date': '28-05-2025', 'nav': '192.23220'},
  {'date': '27-05-2025', 'nav': '191.69150'},
  {'date': '26-05-2025', 'nav': '192.01160'},
  {'date': '23-05-2025', 'nav': '190.74280'},
  {'date': '22-05-2025', 'nav': '190.22970'},
  {'date': '21-05-2025', 'nav': '190.27080'},
  {'date': '20-05-2025', 'nav': '190.16200'},
  {'date': '19-05-2025', 'nav': '192.00150'},
  {'date': '16-05-2025', 'nav': '190.55430'},
  {'date': '15-05-2025', 'nav': '189.77160'},
  {'date': '14-05-2025', 'nav': '188.34010'},
  {'date': '13-05-2025', 'nav': '185.91990'},
  {'date': '12-05-2025', 'nav': '185.51940'},
  {'date': '09-05-2025', 'nav': '180.30790'},
  {'date': '08-05-2025', 'nav': '181.21480'},
  {'date': '07-05-2025', 'nav': '182.51470'},
  {'date': '06-05-2025', 'nav': '180.87420'},
  {'date': '05-05-2025', 'nav': '183.67000'},
  {'date': '02-05-2025', 'nav': '181.67630'},
  {'date': '30-04-2025', 'nav': '181.85270'},
  {'date': '29-04-2025', 'nav': '184.47490'},
  {'date': '28-04-2025', 'nav': '184.79840'},
  {'date': '25-04-2025', 'nav': '184.38920'},
  {'date': '24-04-2025', 'nav': '187.44420'},
  {'date': '23-04-2025', 'nav': '187.49180'},
  {'date': '22-04-2025', 'nav': '187.45940'},
  {'date': '21-04-2025', 'nav': '186.10860'},
  {'date': '17-04-2025', 'nav': '183.49400'},
  {'date': '16-04-2025', 'nav': '182.67970'},
  {'date': '15-04-2025', 'nav': '181.46880'},
  {'date': '11-04-2025', 'nav': '177.35900'},
  {'date': '09-04-2025', 'nav': '173.40240'},
  {'date': '08-04-2025', 'nav': '174.61980'},
  {'date': '07-04-2025', 'nav': '171.89300'},
  {'date': '04-04-2025', 'nav': '176.88530'},
  {'date': '03-04-2025', 'nav': '181.02050'},
  {'date': '02-04-2025', 'nav': '180.50400'},
  {'date': '01-04-2025', 'nav': '178.30730'},
  {'date': '31-03-2025', 'nav': '178.56280'},
  {'date': '28-03-2025', 'nav': '178.55480'},
  {'date': '27-03-2025', 'nav': '178.65350'},
  {'date': '26-03-2025', 'nav': '178.86170'},
  {'date': '25-03-2025', 'nav': '181.14990'},
  {'date': '24-03-2025', 'nav': '181.66260'},
  {'date': '21-03-2025', 'nav': '179.87650'},
  {'date': '20-03-2025', 'nav': '177.25460'},
  {'date': '19-03-2025', 'nav': '176.27700'},
  {'date': '18-03-2025', 'nav': '174.30650'},
  {'date': '17-03-2025', 'nav': '170.84150'},
  {'date': '13-03-2025', 'nav': '170.44540'},
  {'date': '12-03-2025', 'nav': '170.91270'},
  {'date': '11-03-2025', 'nav': '170.81180'},
  {'date': '10-03-2025', 'nav': '171.88780'},
  {'date': '07-03-2025', 'nav': '173.64640'},
  {'date': '06-03-2025', 'nav': '173.05460'},
  {'date': '05-03-2025', 'nav': '170.53780'},
  {'date': '04-03-2025', 'nav': '167.41440'},
  {'date': '03-03-2025', 'nav': '166.53630'},
  {'date': '28-02-2025', 'nav': '167.27530'},
  {'date': '27-02-2025', 'nav': '169.27610'},
  {'date': '25-02-2025', 'nav': '170.57720'},
  {'date': '24-02-2025', 'nav': '171.02810'},
  {'date': '21-02-2025', 'nav': '173.19400'},
  {'date': '20-02-2025', 'nav': '173.72510'},
  {'date': '19-02-2025', 'nav': '172.85420'},
  {'date': '18-02-2025', 'nav': '170.63510'},
  {'date': '17-02-2025', 'nav': '172.60170'},
  {'date': '14-02-2025', 'nav': '173.70270'},
  {'date': '13-02-2025', 'nav': '177.22140'},
  {'date': '12-02-2025', 'nav': '178.06730'},
  {'date': '11-02-2025', 'nav': '178.80970'},
  {'date': '10-02-2025', 'nav': '183.49470'},
  {'date': '07-02-2025', 'nav': '186.60010'},
  {'date': '06-02-2025', 'nav': '188.22360'},
  {'date': '05-02-2025', 'nav': '188.00120'},
  {'date': '04-02-2025', 'nav': '187.74020'},
  {'date': '03-02-2025', 'nav': '186.58870'},
  {'date': '31-01-2025', 'nav': '185.89270'},
  {'date': '30-01-2025', 'nav': '183.94810'},
  {'date': '29-01-2025', 'nav': '184.47400'},
  {'date': '28-01-2025', 'nav': '179.99810'},
  {'date': '27-01-2025', 'nav': '181.15050'},
  {'date': '24-01-2025', 'nav': '184.83570'},
  {'date': '23-01-2025', 'nav': '187.60260'},
  {'date': '22-01-2025', 'nav': '186.99250'},
  {'date': '21-01-2025', 'nav': '189.03020'},
  {'date': '20-01-2025', 'nav': '191.86990'},
  {'date': '17-01-2025', 'nav': '190.54740'},
  {'date': '16-01-2025', 'nav': '191.54610'},
  {'date': '15-01-2025', 'nav': '190.29080'},
  {'date': '14-01-2025', 'nav': '189.43940'},
  {'date': '13-01-2025', 'nav': '187.97080'},
  {'date': '10-01-2025', 'nav': '194.09510'},
  {'date': '09-01-2025', 'nav': '197.39780'},
  {'date': '08-01-2025', 'nav': '199.10830'},
  {'date': '07-01-2025', 'nav': '201.51000'},
  {'date': '06-01-2025', 'nav': '199.93250'},
  {'date': '03-01-2025', 'nav': '204.74730'},
  {'date': '02-01-2025', 'nav': '204.95800'},
  {'date': '01-01-2025', 'nav': '204.01330'},
  {'date': '31-12-2024', 'nav': '202.02500'},
  {'date': '30-12-2024', 'nav': '200.94740'},
  {'date': '27-12-2024', 'nav': '202.27440'},
  {'date': '26-12-2024', 'nav': '201.17120'},
  {'date': '24-12-2024', 'nav': '201.91170'},
  {'date': '23-12-2024', 'nav': '201.82350'},
  {'date': '20-12-2024', 'nav': '203.86390'},
  {'date': '19-12-2024', 'nav': '208.18140'},
  {'date': '18-12-2024', 'nav': '208.90390'},
  {'date': '17-12-2024', 'nav': '209.14900'},
  {'date': '16-12-2024', 'nav': '209.93610'},
  {'date': '13-12-2024', 'nav': '209.47050'},
  {'date': '12-12-2024', 'nav': '209.13640'},
  {'date': '11-12-2024', 'nav': '210.48870'},
  {'date': '10-12-2024', 'nav': '210.19360'},
  {'date': '09-12-2024', 'nav': '209.11880'},
  {'date': '06-12-2024', 'nav': '207.77930'},
  {'date': '05-12-2024', 'nav': '206.96340'},
  {'date': '04-12-2024', 'nav': '206.87990'},
  {'date': '03-12-2024', 'nav': '205.61420'},
  {'date': '02-12-2024', 'nav': '203.06620'},
  {'date': '30-11-2024', 'nav': '203.23060'},
  {'date': '29-11-2024', 'nav': '203.22980'},
  {'date': '28-11-2024', 'nav': '202.20460'},
  {'date': '27-11-2024', 'nav': '202.23030'},
  {'date': '26-11-2024', 'nav': '201.59810'},
  {'date': '25-11-2024', 'nav': '201.24270'},
  {'date': '22-11-2024', 'nav': '196.96790'},
  {'date': '21-11-2024', 'nav': '196.01740'},
  {'date': '19-11-2024', 'nav': '196.91490'},
  {'date': '18-11-2024', 'nav': '194.96320'},
  {'date': '14-11-2024', 'nav': '195.88250'},
  {'date': '13-11-2024', 'nav': '194.60350'},
  {'date': '12-11-2024', 'nav': '198.66500'},
  {'date': '11-11-2024', 'nav': '201.17830'},
  {'date': '08-11-2024', 'nav': '202.85580'},
  {'date': '07-11-2024', 'nav': '204.91850'},
  {'date': '06-11-2024', 'nav': '205.59320'},
  {'date': '05-11-2024', 'nav': '203.88450'},
  {'date': '04-11-2024', 'nav': '204.18210'},
  {'date': '31-10-2024', 'nav': '204.70650'},
  {'date': '30-10-2024', 'nav': '201.17000'},
  {'date': '29-10-2024', 'nav': '199.66210'},
  {'date': '28-10-2024', 'nav': '198.76200'},
  {'date': '25-10-2024', 'nav': '199.02570'},
  {'date': '24-10-2024', 'nav': '202.37940'},
  {'date': '23-10-2024', 'nav': '204.16040'},
  {'date': '22-10-2024', 'nav': '204.11900'},
  {'date': '21-10-2024', 'nav': '209.18120'},
  {'date': '18-10-2024', 'nav': '212.42580'},
  {'date': '17-10-2024', 'nav': '212.58360'},
  {'date': '16-10-2024', 'nav': '214.61380'},
  {'date': '15-10-2024', 'nav': '214.67670'},
  {'date': '14-10-2024', 'nav': '212.70610'},
  {'date': '11-10-2024', 'nav': '211.86820'},
  {'date': '10-10-2024', 'nav': '211.20750'},
  {'date': '09-10-2024', 'nav': '211.46180'},
  {'date': '08-10-2024', 'nav': '209.71250'},
  {'date': '07-10-2024', 'nav': '205.93070'},
  {'date': '04-10-2024', 'nav': '210.64500'},
  {'date': '03-10-2024', 'nav': '211.10730'},
  {'date': '01-10-2024', 'nav': '214.27590'},
  {'date': '30-09-2024', 'nav': '213.85410'},
  {'date': '27-09-2024', 'nav': '213.82450'},
  {'date': '26-09-2024', 'nav': '212.39300'},
  {'date': '25-09-2024', 'nav': '213.20710'},
  {'date': '24-09-2024', 'nav': '212.94540'},
  {'date': '23-09-2024', 'nav': '213.66070'},
  {'date': '20-09-2024', 'nav': '212.07530'},
  {'date': '19-09-2024', 'nav': '211.29030'},
  {'date': '18-09-2024', 'nav': '212.19740'},
  {'date': '17-09-2024', 'nav': '212.87130'},
  {'date': '16-09-2024', 'nav': '213.11800'},
  {'date': '13-09-2024', 'nav': '212.68240'},

In [35]:
data.keys()

dict_keys(['meta', 'data', 'status'])

In [36]:
data["meta"]

{'fund_house': 'SBI Mutual Fund',
 'scheme_type': 'Open Ended Schemes',
 'scheme_category': 'Equity Scheme - Small Cap Fund',
 'scheme_code': 125497,
 'scheme_name': 'SBI Small Cap Fund - Direct Plan - Growth',
 'isin_growth': 'INF200K01T51',
 'isin_div_reinvestment': None}

In [37]:
data["data"][:5]

[{'date': '02-06-2026', 'nav': '193.12950'},
 {'date': '01-06-2026', 'nav': '192.31950'},
 {'date': '31-05-2026', 'nav': '193.68360'},
 {'date': '29-05-2026', 'nav': '193.68480'},
 {'date': '27-05-2026', 'nav': '195.05010'}]

In [38]:
nav_df = pd.DataFrame(data["data"])

In [39]:
nav_df.head()

         date        nav
0  02-06-2026  193.12950
1  01-06-2026  192.31950
2  31-05-2026  193.68360
3  29-05-2026  193.68480
4  27-05-2026  195.05010

In [40]:
nav_df.to_csv(
    "../data/raw/hdfc_top100_nav.csv",
    index=False
)

In [41]:
import os

os.listdir("../data/raw")

['01_fund_master.csv',
 '02_nav_history.csv',
 '03_aum_by_fund_house.csv',
 '04_monthly_sip_inflows.csv',
 '05_category_inflows.csv',
 '06_industry_folio_count.csv',
 '07_scheme_performance.csv',
 '08_investor_transactions.csv',
 '09_portfolio_holdings.csv',
 '10_benchmark_indices.csv',
 'hdfc_top100_nav.csv']

In [42]:
import requests
import pandas as pd

schemes = {
    "sbi_bluechip": 119551,
    "icici_bluechip": 120503,
    "nippon_large_cap": 118632,
    "axis_bluechip": 119092,
    "kotak_bluechip": 120841
}

for name, code in schemes.items():

    url = f"https://api.mfapi.in/mf/{code}"

    response = requests.get(url)

    data = response.json()

    nav_df = pd.DataFrame(data["data"])

    nav_df.to_csv(
        f"../data/raw/{name}_nav.csv",
        index=False
    )

    print(f"Saved {name}_nav.csv")

Saved sbi_bluechip_nav.csv
Saved icici_bluechip_nav.csv
Saved nippon_large_cap_nav.csv
Saved axis_bluechip_nav.csv
Saved kotak_bluechip_nav.csv

In [43]:
import os

for file in os.listdir("../data/raw"):
    print(file)

01_fund_master.csv
02_nav_history.csv
03_aum_by_fund_house.csv
04_monthly_sip_inflows.csv
05_category_inflows.csv
06_industry_folio_count.csv
07_scheme_performance.csv
08_investor_transactions.csv
09_portfolio_holdings.csv
10_benchmark_indices.csv
axis_bluechip_nav.csv
hdfc_top100_nav.csv
icici_bluechip_nav.csv
kotak_bluechip_nav.csv
nippon_large_cap_nav.csv
sbi_bluechip_nav.csv